### ISSUE TITLE
Failed to execute run.py

### ISSUE THREAD

**Issue by pentium3** [malin1993ml/QueryBot5000#3]
Hi. I tried the code by executing run.py, but it failed at this point:

`
time python3 forecaster/exp_multi_online_continuous.py tiramisu --method rnn --aggregate 60 --horizon 4320 --input_dir online-clusters/ --cluster_path cluster-coverage/coverage.pickle --output_dir prediction-results/
1.csv
43.csv
6.csv
7.csv
2016-12-10 21:13:00 2016-11-30 21:13:00 2016-12-13 21:13:00
(312, 3)
(216, 3)
(264, 3)
epoch:  1
Traceback (most recent call last):
  File "forecaster/exp_multi_online_continuous.py", line 757, in <module>
    args['input_dir'], args['output_dir'], args['cluster_path'])
  File "forecaster/exp_multi_online_continuous.py", line 738, in Main
    Predict(args, config, top_cluster, trajs, method)
  File "forecaster/exp_multi_online_continuous.py", line 643, in Predict
    train_pass(args, method, model, train_data, criterion, lr, args.bptt, args.clip, args.log_interval)
  File "forecaster/exp_multi_online_continuous.py", line 341, in train_pass
    hidden = Utilities.repackage_hidden(hidden)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/home/tidb/Desktop/QueryBot5000/forecaster/Utilities.py", line 24, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 384, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

real	0m1.330s
user	0m1.429s
sys	0m1.232s
Execution time: 1 seconds
output_dir: prediction-results/agg-60/horizon-4320/ensemble/
1.csv prediction-results/agg-60/horizon-4320/ar/1.csv
43.csv prediction-results/agg-60/horizon-4320/ar/43.csv
6.csv prediction-results/agg-60/horizon-4320/ar/6.csv
Traceback (most recent call last):
  File "./forecaster/generate_ensemble_hybrid.py", line 120, in <module>
    Main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "./forecaster/generate_ensemble_hybrid.py", line 97, in Main
    data = GenerateData([data_dict1[file_name], data_dict2[file_name]])
KeyError: '1.csv'
output_dir: prediction-results/agg-60/horizon-4320/hybrid/
1.csv prediction-results/agg-60/horizon-4320/kr/1.csv
43.csv prediction-results/agg-60/horizon-4320/kr/43.csv
6.csv prediction-results/agg-60/horizon-4320/kr/6.csv
`

I have installed all the requirements. So how to solve this issue? 
Thank you.

**Comment by linmagit** [comment]
Thanks for posting this! It turns out to be that the code I wrote for the old version of PyTorch does not work for the newer version PyTorch anymore. I've updated the code to fix this in https://github.com/malin1993ml/QueryBot5000/commit/58908dcd6d542b935dd8aa0f62b2dfe78430f61e.
